### ISSUE TITLE
Face Detection Max Face Size

### ISSUE THREAD

**Issue by manb911** [bdtinc/maskcam#10]
There seems to be a threshold of maximum face size, when I get close enough to the camera seems like the detection doesn't see a face. Is there a size guide for the weight of Yolo Detection you are using? Thank you

**Comment by DonBraulio** [comment]
Hey @manb911 , that's a good catch. Since our camera is not intended to be used in a "webcam" setup, the vast majority of training images contained faces at a certain distance, as you would see on most real camera scenarios.
So, even though there's no specific threshold for maximum face size, the detector won't work well in such cases. Unfortunately there's no quick fix that I can think of for that problem, other than retraining the model. Or, somehow resizing the model input, if you don't care that it will perform worse for distant faces.
