### ISSUE TITLE
Add video file manually rather than fetching from camera

### ISSUE THREAD

**Issue by collabnix** [bdtinc/maskcam#6]
How to add a video file rather than live stream from camera device for Mask detection?

**Comment by DonBraulio** [comment]
Hi @collabnix,
thanks for your question! I see it's not covered in the README (although there are other input examples [here](https://github.com/bdtinc/maskcam#setting-device-configuration-parameters))
You need to set `MASKCAM_INPUT=file:///absolute/path/to/file`. Note that it needs to be the full (not relative) path as seen **from the container**. You'll probably need to mount a docker volume binding the folder where the video is located. For example:
```bash
docker run ... -v /host/path/to/video/folder:/videos --env MASKCAM_INPUT=file:///videos/video.mp4 ...
```
Then copy the generated video file in the container, back to the `/videos` folder to see it from the host machine.
Hope this is useful!

**Comment by prabhd33ps** [comment]
It might be a silly question but the docker terminates as it completes the process. How to copy back the processed video back to host?

**Comment by DonBraulio** [comment]
Actually it's a good question! I can think of two options for that:
* Run in [development mode](https://github.com/bdtinc/maskcam#development-mode-manually-running-maskcam) so that you can run the script manually as explained there, and then you can copy the resulting `output_...mp4` video to the host volume.
* Change the default output path to a shared volume. Unfortunately there's not yet a config param to set the output folder, but you can change [this line](https://github.com/bdtinc/maskcam/blob/4841c2c49235844765e8c2164f5dd03a7d28bdad/maskcam_run.py#L466) in the code.
